# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetryMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetryMessage.proto',
  package='telemetrypackage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16telemetryMessage.proto\x12\x10telemetrypackage\"\x92\x01\n\x10TelemetryMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05\x61ngle\x18\x04 \x01(\x05\x12\n\n\x02ll\x18\x05 \x01(\t\x12\n\n\x02ul\x18\x06 \x01(\t\x12\n\n\x02rl\x18\x07 \x01(\t\x12\n\n\x02\x62l\x18\x08 \x01(\t\x12\x0f\n\x07\x62\x61ttery\x18\t \x01(\x05\x12\x0c\n\x04type\x18\n \x01(\tb\x06proto3')
)




_TELEMETRYMESSAGE = _descriptor.Descriptor(
  name='TelemetryMessage',
  full_name='telemetrypackage.TelemetryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='telemetrypackage.TelemetryMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='telemetrypackage.TelemetryMessage.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='telemetrypackage.TelemetryMessage.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='telemetrypackage.TelemetryMessage.angle', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ll', full_name='telemetrypackage.TelemetryMessage.ll', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ul', full_name='telemetrypackage.TelemetryMessage.ul', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rl', full_name='telemetrypackage.TelemetryMessage.rl', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bl', full_name='telemetrypackage.TelemetryMessage.bl', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='telemetrypackage.TelemetryMessage.battery', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='telemetrypackage.TelemetryMessage.type', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['TelemetryMessage'] = _TELEMETRYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TelemetryMessage = _reflection.GeneratedProtocolMessageType('TelemetryMessage', (_message.Message,), dict(
  DESCRIPTOR = _TELEMETRYMESSAGE,
  __module__ = 'telemetryMessage_pb2'
  # @@protoc_insertion_point(class_scope:telemetrypackage.TelemetryMessage)
  ))
_sym_db.RegisterMessage(TelemetryMessage)


# @@protoc_insertion_point(module_scope)
