# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uiCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uiCommand.proto',
  package='telemetrypackage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fuiCommand.proto\x12\x10telemetrypackage\"8\n\x10UiCommandMessage\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x62\x06proto3')
)




_UICOMMANDMESSAGE = _descriptor.Descriptor(
  name='UiCommandMessage',
  full_name='telemetrypackage.UiCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='telemetrypackage.UiCommandMessage.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='telemetrypackage.UiCommandMessage.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='telemetrypackage.UiCommandMessage.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['UiCommandMessage'] = _UICOMMANDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UiCommandMessage = _reflection.GeneratedProtocolMessageType('UiCommandMessage', (_message.Message,), dict(
  DESCRIPTOR = _UICOMMANDMESSAGE,
  __module__ = 'uiCommand_pb2'
  # @@protoc_insertion_point(class_scope:telemetrypackage.UiCommandMessage)
  ))
_sym_db.RegisterMessage(UiCommandMessage)


# @@protoc_insertion_point(module_scope)
